name: iOS CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-15

    steps:
      - name: Install Pre-Req.
        run: |
          brew install swiftlint
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Bundler
        run: gem install bundler
      - name: Install Gems
        run: bundle install --jobs 4 --retry 3
      - name: Create TEMP folder
        run: bundle exec fastlane create_temp
      - name: Decode Certificate
        run: |
          echo "$DEVELOPMENT_CERTIFICATE" | base64 --decode > dev_certificate.p12
          security create-keychain -p "" build.keychain
          security import dev_certificate.p12 -k build.keychain -P "$CERT_PASSWORD" -T /usr/bin/codesign
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain
        env:
          DEVELOPMENT_CERTIFICATE: ${{ secrets.DIST_CERT }}
          CERT_PASSWORD: ${{ secrets.DIST_PASS }}
      - name: Decode and Install Provisioning Profile
        run: |
          echo "$DEV_PROVISION" | base64 --decode > dev.mobileprovision
          fastlane run install_provisioning_profile path:dev.mobileprovision
          echo "$PROD_PROVISION" | base64 --decode > prod.mobileprovision
          fastlane run install_provisioning_profile path:prod.mobileprovision
        env:
          DEV_PROVISION: ${{ secrets.DEV_PROVISION }}
          PROD_PROVISION: ${{ secrets.PROD_PROVISION }}
      - name: Lint
        run: |
          bundle exec fastlane lint
      - name: Build & Test
        run: |
          bundle exec fastlane build_and_test --env development
      - name: Deploy DEV
        run: |
          bundle exec fastlane build_and_deploy --env development
        env:
          GITHUB_TOKEN: ${{ secrets.GHB_TOKEN }}
      - name: Deploy PROD
        run: |
          bundle exec fastlane build_and_distribute --env prod
        env:
          GITHUB_TOKEN: ${{ secrets.GHB_TOKEN }}
      - name: Remove Leftovers
        run: bundle exec fastlane remove_leftovers
